Imporved the script

diff --git a/miscfiles/scripts/picbin b/miscfiles/scripts/picbin
--- a/miscfiles/scripts/picbin
+++ b/miscfiles/scripts/picbin
@@ -1,13 +1,49 @@
 #/bin/bash
 # @Auther Stephen Cochrane
 set -e
-kill () {
+
+usage () {
 	echo "<usage> picbin /path/to/picture"
-	exit 1
+	exit $1
 }
 
-[ 0 -eq $# ] && kill
-[[ ! -f $1 ]] && kill
+while getopts "hp:l" opt
+do
+	case $opt in
+		h)
+			usage 0
+			;;
+		p)
+			path="$OPTARG"
+			;;
+		l)
+			link=1
+			;;
+		*)
+			exit 2
+			;;
+	esac
+done
 
-echo $1
-curl -F"file=@$1" https://0x0.st
+if [ $path ]
+then
+	[ 0 -eq $# ] && usage 1
+	[[ ! -f $path ]] && usage 1
+else
+	gnome-screenshot -f /tmp/picbin.png
+	path="/tmp/picbin.png"
+fi
+
+abort() {
+	echo "Aborting upload of $path"
+	exit 0
+}
+
+zenity --question --text="Confirm upload."
+[ ! $? ] && abort
+
+echo "Uploading -> $path"
+
+url=$(curl -F"file=@$path" https://0x0.st)
+echo $url
+[ $link ] && zenity --info --window-icon="info" --text="$url" || exit 0
